apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-deployment
  labels:
    app: coredns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns
        ports:
        - containerPort: 53
